title: Open Science # your site title
author: Sebastian Schwindt
email: sschwindt[at]ucdavis.edu # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  The reproducibility of scientific analyses is a hallmark of sound research. Python codes are the backbone of my data analysis and this repository provides these codes.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sschwindt.github.io/OpenScience/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sschwindt # replace with your_github_username or comment to remove link from footer
social:
  name: Sebastian Schwindt
  links:
    - https://www.researchgate.net/profile/Sebastian_Schwindt
    - http://www.linkedin.com/in/sebastian-schwindt
    - https://scholar.google.ch/citations?user=GdmFKPgAAAAJ&hl=de&oi=ao
    - https://github.com/sschwindt

disqus:
  shortname: sschwindt # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
