title: Open Science Data
description: > # this means to ignore newlines until "baseurl:"
  The reproducibility of scientific analyses is a hallmark of sound research. 
permalink: ':title/'
baseurl: "/OpenScience" # the subpath of your site, e.g. /blog
url: "https://github.com/sschwindt" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author: Sebastian Schwindt # add your name
author-img: water.jpg # add your photo
about-author: Codes and data used in published research by Sebastian Schwindt.
social-github: sschwindt # add your Github handle
social-linkedin: sebastian-schwindt # add your Linkedin handle
social-email: sschwindt[at]ucdavis.edu # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: 113195988 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 20
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
